[package]
name = "day-7"
version = "0.1.0"
edition = "2024"

[dependencies]
tinysetqueue = "^0.2"

[features]
default = []
part2 = []
sample = []
std = []

[dev-dependencies]
divan = "^0.1"
gag = "^1.0"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
